name: open_app_file_example
description: Demonstrates how to use the open_app_file plugin.

version: 4.0.1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  path_provider: ^2.0.11
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  open_app_file:
    path: ../

flutter:
  uses-material-design: true
