name: open_app_file
description: A plug-in that can call native APP to open files with string result in flutter, support iOS(UTI) / android(intent) / PC(ffi) / web(dart:html)
version: 3.2.3
homepage: https://github.com/yendoplan/open_app_file

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.12.0"

flutter:
  plugin:
    platforms:
      android:
        package: com.yendoplan.openappfile
        pluginClass: OpenAppFilePlugin
      ios:
        pluginClass: OpenAppFilePlugin
